version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: Frontend
    ports:
      - "8000:80"
    restart: unless-stopped
    links:
      - backend
  breacher-backend:
    build: Backend
    restart: unless-stopped
    # ports:
    #   - "8083:5000"