apiVersion: v1
kind: Service
metadata:
  name: breacher-frontend
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: breacher-frontend
    tier: frontend
  type: LoadBalancer